spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 10000
  datasource:
    druid:
      name: almas-test
      url: jdbc:mysql://localhost:3306/dawn?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      validationQuery: SELECT 1 FROM DUAL
      filters: [stat,wall,log4j]
      useGlobalDataSourceStat: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
      web-stat-filter:
        enabled: true
        url-pattern: /*


mybatis-plus:
  typeAliasesPackage: com.yyovo.almas.**.model.pojo
  typeEnumsPackage: com.yyovo.almas.**.model.enums
  #  mapperLocations:/
  #  mapperLocations: classpath*:/mapper/**/*.xml
  configuration:
    #自动驼峰命名规则
    map-underscore-to-camel-case: true
  global-config:
    superMapperClass: com.yyovo.almas.common.base.dao.SuperMapper
    db-config:
      table-prefix: y_
